// Common English word list for Boggle validation (3–8 letters)
const WORDS = new Set((
'ace act add age ago aid aim air ale all ant any ape apt arc are ark arm art ash ask ate awe axe aye ' +
'bad bag ban bar bat bay bed beg bet bid big bit bow box boy bud bug bun bus but buy ' +
'cab can cap car cat cob cod cop cow cry cub cup cut ' +
'dad dam day den dew did die dig dim dip dog dot dry due dug dye ' +
'ear eat egg ego elf elm end era eve ewe eye ' +
'fad fan far fat fee few fig fin fit fix fly foe fog for fox fry fun fur ' +
'gap gas gem get gin gnu god got gum gun gut guy ' +
'had ham has hat hay hen her hid him hip his hit hoe hog hop hot how hub hug hum hut ' +
'ice ill inn ion its ivy ' +
'jab jar jaw jet job jot joy jug jut ' +
'keg kin kit ' +
'lab lad lap law lay led leg lid lip lit log lot low ' +
'mad map mar mat may men met mob mop mud mug ' +
'nag nap net new nil nip not now nun ' +
'oak oar odd off oil old one opt orb ore our out owl own ' +
'pad pan pat paw pay pea peg pen pie pig pin pit ply pod pot pub pun pup put ' +
'ran rat raw ray red rip rob rod rot row rub rug run rut rye ' +
'sad sag sap sat say sea set sew she shy sin sir sit ski sky sob sod son sow spa spy sue sun ' +
'tab tan tap tar ten tip toe too top toy try tub tug two ' +
'urn use ' +
'van vat vet via vow ' +
'wag was wax web wed wet who why wig win wit woe won woo ' +
'yak yam yet yew you ' +
'zap zip zoo ' +
'able ache acid acre aged aide aims airs alms also alto amid amps ante arch area aria arid army arts ' +
'back bake bale ball band bane bang bank bare barn base bath bead beat beef been beer bell belt bend best bile bind bird bite bled blob blow blue blur body boil bold bolt bond bone book boom bore born boss both bout bowl brew buff bull burn bush busy ' +
'cafe cage cake call calm came camp cane cape card care cart case cash cast cave cell chef chew chin chip chop cite clam clap claw clay clip clot clue coal coat code coil coin cold colt come cone cope core corn cost cove crab cram crop crow cube cure curl cute cyan ' +
'dale dame damp dare dark dart data date dawn daze dead deaf deal dear debt deck deep deer demo deny desk dice died dies diet digs dime dine dire dirt dish disk dock dome done dose dove down drag draw drip drop drum duck dull dumb dump dust ' +
'earl earn ease east edge emit epic even ever evil exam ' +
'face fact fade fail fair fake fall fame fang fare farm fast fate feat feed feel fell felt fend fern file fill film find fine firm fish fist five flag flat flea fled flex flip flow foam foil fond fool ford fore fork form fort foul fowl fray free frog from fuel full fume fuse ' +
'gale gang gape gash gate gave gaze gear geld germ glee glow glue glum gnat goal goat gold golf gone grab grit grub gust ' +
'hack hail hale half hall halo halt hand hang hard hare harm harp haze head heal heap hear heat heel herb herd hero high hike hill hint hire hive hoax hock hold hole holy home hood hoop hope horn hose host hour huge hulk hull hunt hurl hymn ' +
'idle itch ' +
'jade jail joke jolt jump jury just ' +
'keel keen kept keys kids kill kind king knob knot ' +
'lack laid lame lamp land lane lard lark last late lawn lead leaf leak lean leap leek lend lens lent levy lies lift lime limp line lion list live load loaf lock loft lone long look lore lose loss loud love luck lull lure lust lute lyre ' +
'made maid mail main make mane many mark mart mash mast math maze meal mean meat meek mesh mist mock mode mole molt moon moor mope more morn most move much muse musk must mute myth ' +
'nail name nape need news nice nick node nose note noun nova null numb ' +
'pace pact page paid pail pair palm pang park part pass past path pave pawn peel peer pens pest pick pile pill pine pink pipe pity plan plot plow ploy plum poet pole pond poor pope pork port pose post pour pout pray prep prey prod prop prow pull pulp pump pure push ' +
'race rack raid rail rain rake ramp rant rare rash rate rave read real reed reef reel rely rend rent rest rice rich ride rife ring riot rise risk road roam roar robe rode role roll roof root rope rose rout rove ruin rule rump rush rust ' +
'safe sage sail sake sale salt same sand sane sang sash save scan scar seam seep self send sent serf shed shin ship shop shot shun shut silk sing sire size skim skip slam slap slay sled slim slip slop slow slug slum smug snag snap snob snug soak soap sock sofa soil sold some song sore sort soul soup sour span spit spot spur stab star stay stem step stew stub stud stun such suit sung sunk swan swap ' +
'tack tale tall tame tang task taut team teal tear tell tend tent term test that thin this toil tone tool torn toss tout town trip trim trod true tube tuft tuna tune turf twin ' +
'ugly unit upon ' +
'vain vale vane vent verb very vest veto vice vine void vote ' +
'wade wail wait wake wane ward ware warn wary wave weak weal weed weep weld went west wide wile will wilt wind wine wing wink wire wise wish woke wolf word wore wrap wren ' +
'zeal zest zinc zone zoom ' +
'abbey abide abode above abuse abyss ached acorn acres acted added adept adult afoot after again agent agile agony agree ahead aided aimed aired aisle alarm album alert alien align alike alive allay alley allow aloft alter amber amble amend ample amuse angel anger angle angry ankle annex antic anvil apple aptly arbor ardor aroma arose array attic audio augur avail avert awoke azure ' +
'badge basic basis baton beach beard beast began being below berry blast blaze bleed blend bless blind bliss bloom blown blunt board boast boost bound braid brave bread break brisk brood broth broom brunt budge bulge bully bunch burst ' +
'cadge cameo candy cargo carry caste catch cause cedar chase cheap cheer chess chick child china chord circa civic civil claim clamp clash clasp class cling clock close cloth clout cobra comet comic comma coral crane craze creak cream creek crisp cross crumb crust cycle ' +
'daisy dance daunt decry delay delta dense depot digit dirty dizzy dodge dough draft drain drama drape drawn dread dream dress drift drink drove drown elbow elite ember empty enact enter envoy erupt evade event exact exert exist exult ' +
'fable faint faith fancy farce feast fetch fiery flair flame flare flash flesh float flood floor flour flute foamy foray forge found foyer frame frank fraud frown froze fugue fungi ' +
'gauze gaudy gavel gecko giddy given gland glare glean glide globe gloom gloss glove gnome gouge gourd grace grade grain grand grasp gravy graze greed greet grief groan groat groin gross grove growl guild guile guise ' +
'haiku hasty haven heard heart heist herby hills hobby hoist holly honor hotel hound hover humid humor hurry hyena ' +
'idler idiom inept infer inlet inner inset inter intro ionic irate ivory ' +
'joust kayak kneel lance lapel laser latch later leach leafy leapt ledge lemon level lithe liver lofty logic lusty ' +
'maple march marsh matte medal merry metal mills mirth mimic miser moody moral mourn muddy mulch naive niche night noble notch novel nudge nymph ' +
'offer often olive onion optic orbit order other ought ounce oxide ozone ' +
'padre paint panic pansy paper parch party pasta peace pearl pedal penal penny perch peril petty phase phone piano pilot pinch pixel pizza plaid plain plane plank plant plaza plumb plume plunk plush poker polar poppy pouch power prank press pride prime prism probe prone proud prove psalm puppy ' +
'queen quest quick quiet quill quota quote ' +
'rabbi radar raise rally range rapid ratio razor reach realm rebut regal reign relax repay repel retro rider risky roast robin rocky roomy rouge round rowdy royal ruddy rugby ruler runic rural ' +
'sabre sadly saint salve salvo samba sandy sassy sauce saucy savvy scope scorn scour scout scram seize setup seven shaft shaky shame shape shark sheen sheep sheet shelf shell shift shine shoal shore shove shown shrub siege silly skirt skunk slack slant slope smart smell smile smoke snare snarl sneak snowy solar solid solve spark spasm spear speck speed spend spice spike spill spine spite split spoke spook sport spout spray spree stain stair stale stall stand stark start stave stealth steer stern stiff still sting stink stomp stony stood story stout stove strap straw stray studs stung style suave sugar suite sulky sunny super surge swamp swear sweat sweep swell swept swift swore synth ' +
'talon tango taunt tawny their theme thick thorn those tiger timed tipsy titan tonic torso total touch tough towel toxic trace track trade trail train trait tramp tread trend trick tried trope trout truck truer truly trump trunk tuber tulip tunic turbo twirl twist tying typed ' +
'unify unite unity undue usher ' +
'vague valor valve vapor vault vigil viral visor vital vivid vocal voter vouch ' +
'waltz waver weary weird wheat wheel where while witch witty woman woods worth wrath wrist wrote ' +
'yacht yearn yield young zebra ' +
'abroad accent access accord accuse across action active actual adapts adhere adjust admire adroit advent advice advise affect affirm afford afghan afield aflame afoot aghast agenda agitate agreed albeit allied allure almond almost almond aloft aloof aloud alpine alters amazon ambush amoeba amount amused amuses anchor anoint antler appeal appear arenas around arouse ascend asleep assert assign assure attach attack attain attire auburn autumn avenue avenge averse avocado awaken awards awning ' +
'backed badger baffled baking ballot bamboo barely barren battle beacon beaker befall befell beggar behind belfry belong bereft bestow bewail beyond bicker binder bison bitter bleach blazed blotch blouse blower boiler bomber borage border boring botany bought bounty branch brandy brawny breeze bridle brimmed broken broker bronze brooch bruise brutal budget bumble bundle bunker burden burglar burrow butter button bypass ' +
'candle cannon career carrot carton carve castle cattle causal cavern cement cereal chance charge charity charm chaste chisel chorus chosen cinder cipher citrus clamor classy cleave clever clover cobalt cobble colony combat compel comply concur condor confer consul consul copper corner costly cotton cougar couplet covert cradle crafty crater crazed creaky credit crispy crotch crumbs crunch cunning cupboard currant cursed dampen dagger darken daydream dealer decade decent deceit defend define deform dented derive desert design devise devour digest direct dither divine divulge domain donkey dotted double doting doubtful dragon drawer driven drizzle drying dungeon during duster ' +
'eating editor egress eighth elated elbow embalm encode endure enfold engage enough ensure entire envy erase errant escape esteem ethics evenly evolve exempt exhale exhume exotic expand expel expose extend extent fading fallow famine fantom fathom faulty feline ferret fetter fickle filler filter finger finite fixate fizzle flannel flappy flaunt flavor fleece flicker flight flounder fluent fodder follow folly fondly fondle forest forget formal fostered foster fright fringe frizzy frolic frozen frugal humble hungry hurdle hyenas ' +
'gallop garlic garner gelatin gentle giggle girder girdle goblin godly gossip gravel grassy gravel griddle grieve grille grimace gristle grizzly grovel grudge grumpy guilty gusted haggis haggle hallow hamlet handle hangar hazard healer hearse hearth hedgehog herald hermit heroic hiatus hidden hinder holler hollow honest hornet hostile hotdog hugely hunter hustle icicle iconic ignite immune impact impede imply import impose incite indeed influx inform innate insane insect inside insist insult intact intend invade invent invest island isolate jargon jarred jester jingle jobless jostle jovial joyful joyous jumble jungle junior jutted kayaks kindle kitten lament landslide laptop larder larges lasting lavish lawful lazily leader leaped legacy lethal likely linden linger liquid listen litter lizard loosen lotion lounge lovable lowest lugged lumber lunged lurked luster luxury ' +
'magnet mallet manage manger mangle mantle margin marvel master mellow menace mental mentor merits method midway mighty mingle minute mirror misery modest molten monkey mortal muffin mugger murmur muscle mystic narrow nature needle nether nibble nimble normal notions novice nuzzle obstacle obstacle obtain offend offset opening orchid outlaw outrun outset oyster palace panels pantry pardon parrot patrol paused pebble peddle pepper petite pillar pitcher pirate placid player pledge pliant plunge pocket possum potent prefer pretty prickle prince prison likely purple pursue puzzle racial random ranger rather rattle ravage raving reckless reduce refine reform relent remind remote render repair resent return reveal revive reward riddle rigorous ringed rising robust roller roughly rugged runway sacred salmon scatter scorch scramble search seduce seeker selfish sermon settle settle shadow shimmer shiver shrink shrewd shrill shrimp sicker signal silver simple single siren sketch skewed sliver sly smooth snuggle somber soothe sorcerer sorrow sorted sparse spiral squall squash squeak squeal squirm stable stagger stammer startle steady stealthy stellar stench sterile stitch stooge stormy streak strife strong struck strung stubborn subtle sucker suffer summon sunder superb surely survey swivel symbol tackle tangle tariff tarnish tasted tattoo tavern tender terror testing tether thirty thorny thread thrill thrive thrown timber tinder tissue toggle toasty toggled toiling topple tossed touchy tougher towering trickle trigger triplet trophy tropical truant trudge tumble tundra tuning turmoil tussle twitch unable unfurl unique unkind untidy uplift uproot useful utmost vacant vaguely vanish vanity varied velvet vendor verify vexing viable victim vilify virtue visual vivify vodka waddle wander warden warped washed waspish weaken weighty whereas willow winner wisdom wistful wither wonder wrench ' +
'abandon abdomen abolish absolve abstain acclaim achieve acquire address advance adverse ailment ailment airborne already ambient amplify ancient appease archaic archive arduous armored arrange arrived arsenal article assault attempt auction audible average barrier bastion bathtub beckons beneath benefit between billion blossom blunder borders bottled bracket bravely breaker briefly brigade builder buzzing cabinet capable capsule captain capture cartoon ceiling channel chapter charity chicken chronic circuit classic climate climber closest coastal cobblestone collect combine comfort command compact compare compel compete complex conquer consult contend context convert correct costume counsel counter country courage covered creator crumble crystal culture curious curious curtain customs cylindrical damage dampen darling daylight despite devious devoted diminish display disturb divided dolphin dormant dormancy dressed drifted durable dynamic dynasty embark embrace empathy employs enclose endless endless endure enforce engulf enhance enough enrich enroll equally equinox essence exhaust exhibit expense extreme ' +
'fantasy fascinated fearful feather federal fifteen focused follows foolish foreign forever forgive forward founded fragile freedom freshly fringes frugally furnish gallant garland gateway genuine gladly glimpse glitter glorious glowing grasping granted gravity greatly gripping grizzled growing habitat hamster handling handsome harbors harmful haunted healing heavenly heroine hidden highest highway holiday hopeful horizon hostile hundred hunting husband ignite imagine immense implore improve income indeed inflate inform inhabit inspire instant intense invent joyful journey justice keeping kindled kingdom knowing knuckle lantern lasting laughter launder lawless learned liberty lifting limited logical longing looking loyalty magical mankind marvel massive meadow meeting mindful mission mistake mistreat mixture modern monster morning morning nightly noticed nourish nowhere nuclear obscure observe obvious onwards opening orchard organic outlast outlook painful partner passion pattern pebbles pendant perhaps persist phantom picture pillow pilgrim pioneer plastered plenty poison polite pottery prevail proceed product protect provide purpose quickly radiant rapidly reality rebuild reckless recover refined reflect release relying remains restore rethink revival reunion reveals revolve rhythm rivalry roaming rooting roughly rousing running sandbox satisfy savanna scholar scratch screech seeking selfish sensory serene shelter shining shrieked shudder slender smiling society somehow soothing sounded sparkling special spiked spotless square squirrel standard starter stately station staying stretch studied sunburn sunrise sunsets survive suspend swarming swiftly symbols tablets telling texture thunder tightly timeless tipping triumph twisted unbroken undergo unknown unleash unready updated upgrade urgent visible wanders warfare watcher wealthy welcome western whether winding without wonders working worries written younger zealous'.split(' ')
).filter(w => w.length >= 3 && w.length <= 8));
